export const SET_TWEETS = "SET_TWEETS";
export const SORT_TWEETS = "SORT_TWEETS";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_FILTER_BOX = "TOGGLE_FILTER_BOX";
export const REQUEST_TWEETS = "REQUEST_TWEETS";
export const RECEIVE_TWEETS = "RECEIVE_TWEETS";
export const APPLY_FILTER = "APPLY_FILTER";
